name: customer
description: GIM is a truck rental app where you can easily create trips anytime, anywhere and move your goods efficiently.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.46+182
#version: 2.0.35+172 //For Android Prod release

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  json_annotation: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Firebase
  firebase_core: ^0.5.0
  firebase_crashlytics: ^0.2.1
  firebase_messaging: ^7.0.2
  firebase_remote_config: ^0.4.0+1
  firebase_dynamic_links: ^0.6.2
  firebase_analytics: ^6.0.1
  firebase_performance: ^0.4.0+1
  flutter_cupertino_localizations: ^1.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  equatable: ^1.0.3
  shared_preferences: ^0.5.3
  sqflite: ^1.1.6
  http: ^0.12.0+2
  flutter_local_notifications: ^1.1.6
  flutter_typeahead: ^1.8.0
  image_picker: ^0.6.2+3
  permission_handler: ^5.0.1+1
  provider: 4.3.2+2
  google_maps_flutter:
  fluster: ^1.1.2
  image_cropper: ^1.1.0
  intl:
  geocoder: ^0.2.1
  location: ^2.4.0
  flutter_image_compress:
  retry: ^3.0.0
  floor: ^0.8.0
  flutter_cupertino_date_picker: ^1.0.12
  flutter_svg: ^0.19.0
  pin_code_text_field: ^1.5.1
  webview_flutter: ^0.3.13
  flutter_webview_plugin:
  url_launcher: ^5.7.2
  cached_network_image: 2.2.0
  pull_to_refresh: ^1.6.2
  flutter_rating_bar:
  auto_size_text: ^2.1.0
  analyzer: ^0.36.4
  wc_flutter_share: ^0.1.1
  screenshot: ^0.1.1
  package_info:
  connectivity:
  device_info: ^0.4.1+5
  flutter_screenutil: ^1.0.2
  flutter_holo_date_picker: ^0.2.1
  flutter_html: ^0.11.1
  path_provider: ^1.5.1
  overlay_support: ^1.0.2
#  flutter_app_badger: 1.1.2

dev_dependencies:
  build_runner: ^1.7.1
  json_serializable: ^3.2.2
  floor_generator: ^0.9.0
  flutter_test:
    sdk: flutter

dependency_override:
  flutter_driver:
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  uses-material-design: true
  assets:
    - assets/licenses.html
    - images/
    - svg_img/
    - locale/localization_en.json
    - locale/localization_bn.json

  fonts:
    - family: roboto
      fonts:
        - asset: fonts/roboto_regular.ttf
          weight: 400
        - asset: fonts/roboto_medium.ttf
          weight: 500
        - asset: fonts/roboto_black.ttf
          weight: 900
        - asset: fonts/roboto_bold.ttf
          weight: 700
        - asset: fonts/roboto_thin.ttf
        - asset: fonts/roboto_light.ttf
          weight: 300
    - family: greatvibes
      fonts:
        - asset: fonts/greatvibes_regular.ttf

    - family: helvetica
      fonts:
        - asset: fonts/helvetica_neue.ttf
        - asset: fonts/helvetica_neue_bold.ttf